title: 'Caffeine Algorithm | Início'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
keywords: 'caffeine algorithm, caffeinealgorithm, desenvolvimento, organização, cafeína, algoritmos, programação, código, python, c#, java, go, javascript, ruby, android, html, css, nelsonsilvadev, nelson silva'
url: 'https://caffeinealgorithm.com/'
baseurl: '/'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'contacto@caffeinealgorithm.com'
  youtube_id: 'UCdt_qK8rmpxrq942ZFIqxvQ'
  youtube_name: 'CaffeineAlgorithm'
  linkedin: 'caffeinealgorithm'
  instagram: 'caffeinealgorithm'
  twitch: 'caffeinealgorithm'
  github: 'caffeinealgorithm'
  website: 'https://caffeinealgorithm.com/'

author:
  name: 'Nelson Silva'
  username: 'nelsonsilvadev'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351913416022'
  location: 'Porto, Portugal'
  email: 'contact@nelsonsilvadev.com'
  bio: 'A human. Being. Coffee lover.'
  linkedin: 'nelsonsilvadev'
  github: 'nelsonsilvadev'
  instagram: 'nelsonsilvadev'
  twitter: 'nelsonsilvadev'
  website: 'https://nelsonsilvadev.com/'

google:
  tag_manager: 'GTM-53K3CN5'
  analytics: 'UA-76965623-1'
  verify: 'E1ZVOTMIuinhdk-ZmrCj9GUXMfKD2yvePOpMehtaLrk'
  ad_client: 'ca-pub-9627952229249296'

features:
  hotjar:
    enable: true
    id: 2360099

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

collections:
  python:
    output: false
    sort_by: id

destination: _site
paginate: 6
paginate_path: /blog/pagina/:num/
permalink: /blog/:year:month:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins: ['jekyll-paginate']
exclude: ['README.md']
