title: 'Caffeine Algorithm'
description: 'Uma organização de desenvolvimento que ama cafeína e algoritmos.'
keywords: 'tecnologia, informática, programação, programador, código, cursos, séries, tutoriais, portugal, brasil, caffeinealgorithm, caffeine algorithm'
url: 'https://caffeinealgorithm.com'

development: false

tagline: 'Aprende a Programar'

organization:
  name: 'Caffeine Algorithm'
  email: 'contacto@caffeinealgorithm.com'
  youtube_id: 'UCdt_qK8rmpxrq942ZFIqxvQ'
  youtube_name: 'CaffeineAlgorithm'
  twitch: 'caffeinealgorithm'
  github: 'caffeinealgorithm'
  linkedin: 'caffeinealgorithm'
  instagram: 'caffeinealgorithm'
  facebook: 'algorithmcaffeine'
  website: 'https://caffeinealgorithm.com/'

author:
  name: 'Nelson Silva'
  username: 'nelsonsilvadev'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351913416022'
  location: 'Porto, Portugal'
  email: 'contact@nelsonsilvadev.com'
  bio: 'A human. Being. Coffee lover.'
  linkedin: 'nelsonsilvadev'
  github: 'nelsonsilvadev'
  instagram: 'nelsonsilvadev'
  website: 'https://nelsonsilvadev.com/'
  url: 'https://nelsonsilvadev.com/'

google:
  tag_manager: 'GTM-53K3CN5'
  analytics: 'UA-76965623-1'
  verify: 'E1ZVOTMIuinhdk-ZmrCj9GUXMfKD2yvePOpMehtaLrk'
  ad_client: 'ca-pub-9627952229249296'

google_site_verification: 'E1ZVOTMIuinhdk-ZmrCj9GUXMfKD2yvePOpMehtaLrk'

facebook:
  admins: 'algorithmcaffeine'

social:
  name: 'Caffeine Algorithm'
  links:
    - 'https://www.youtube.com/c/CaffeineAlgorithm'
    - 'https://www.twitch.tv/caffeinealgorithm'
    - 'https://github.com/caffeinealgorithm'
    - 'https://www.linkedin.com/company/caffeinealgorithm'
    - 'https://www.instagram.com/caffeinealgorithm'
    - 'https://facebook.com/algorithmcaffeine'

locale: 'pt_PT'

seo_paginator_message: 'Página %<current>s de %<total>s | '

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

links:
  - title: Subscreve o Canal
    url: https://www.youtube.com/c/CaffeineAlgorithm?sub_confirmation=1
    color: '#1a1a1a'
    icon: fab fa-youtube

  - title: Todas as Séries de Programação
    url: https://www.youtube.com/c/CaffeineAlgorithm/playlists
    color: '#1a1a1a'
    icon: fas fa-archive

  - title: Acede ao Código Desenvolvido
    url: https://github.com/caffeinealgorithm
    color: '#1a1a1a'
    icon: fas fa-code

  - title: Lê a Última Publicação do Blog
    url: https://caffeinealgorithm.com/blog/
    color: '#1a1a1a'
    icon: fas fa-pen-nib

  - title: Conhece o Fundador
    url: https://nelsonsilvadev.com/
    color: '#1a1a1a'
    icon: fas fa-user

  - title: Novidades da Organização
    url: https://www.linkedin.com/company/caffeinealgorithm
    color: '#1a1a1a'
    icon: fab fa-linkedin

collections:
  anuncios:
    output: false
    sort_by: id
  python:
    output: false
    sort_by: id
  csharp:
    output: false
    sort_by: id

destination: _site
paginate: 6
paginate_path: /blog/pagina/:num/
permalink: /blog/:year:month:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-seo-tag']
exclude: ['README.md']
